### ISSUE TITLE
`etrace file --use-snap-run chromium` fails on Ubuntu 20.10

### ISSUE THREAD

**Issue by oSoMoN** [canonical/etrace#22]
This is in a fully up-to-date groovy (Ubuntu 20.10) amd64 VM:

    ubuntu@groovyvm:~$ etrace file --use-snap-run chromium
    2020/10/23 21:34:34 xdotool.go:84: 
    strace-log-merge: /tmp/file-trace438846678/strace.log: strace output not found
    2020/10/23 21:34:34 file-tracing.go:296: 
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x52ba47]

    goroutine 1 [running]:
    github.com/anonymouse64/etrace/internal/strace.(ExecvePaths).Display(0x0, 0x5dcaa0, 0xc0000ce000)
        /build/etrace/parts/etrace/src/internal/strace/file-tracing.go:173 +0x37
    main.(cmdFile).Execute(0x6ea080, 0xc00005ed20, 0x0, 0x3, 0x0, 0x0)
        /build/etrace/parts/etrace/src/cmd/etrace/cmd_file.go:263 +0xfd0
    github.com/jessevdk/go-flags.(Parser).ParseArgs(0xc00008b730, 0xc000010090, 0x3, 0x3, 0x0, 0x0, 0x0, 0x6, 0xc00007e380)
        /root/go/pkg/mod/github.com/jessevdk/go-flags@v1.4.1-0.20180927143258-7309ec74f752/parser.go:333 +0x8c3
    github.com/jessevdk/go-flags.(Parser).Parse(...)
        /root/go/pkg/mod/github.com/jessevdk/go-flags@v1.4.1-0.20180927143258-7309ec74f752/parser.go:190
    main.main()
        /build/etrace/parts/etrace/src/cmd/etrace/main.go:95 +0x19c

On the other hand, `etrace exec chromium` works as expected in the same VM.

**Comment by anonymouse64** [comment]
I can't reproduce this anymore, can you confirm if you still see this issue?
